#--------------------categories------------------
-
  name: "noise"
  description: "Any lidar return that does not correspond to a physical object, such as dust, vapor, noise, fog, raindrops, smoke and reflections."
  index  : 0

-
  name: "animal"
  description: "All animals, e.g. cats, rats, dogs, deer, birds."
  index  : 1


-
  name: "human.pedestrian.adult"
  description: "Adult subcategory."
  index  : 2


-
  name: "human.pedestrian.child"
  description: "Child subcategory."
  index  : 3


-
  name: "human.pedestrian.construction_worker"
  description: "Construction worker"
  index  : 4


-
  name: "human.pedestrian.personal_mobility"
  description: "A small electric or self-propelled vehicle, e.g. skateboard, segway, or scooters, on which the person typically travels in a upright position. Driver and (if applicable) rider should be included in the bounding box along with the vehicle."
  index  : 5


-
  name: "human.pedestrian.police_officer"
  description: "Police officer."
  index  : 6


-
  name: "human.pedestrian.stroller"
  description: "Strollers. If a person is in the stroller, include in the annotation."
  index  : 7


-
  name: "human.pedestrian.wheelchair"
  description: "Wheelchairs. If a person is in the wheelchair, include in the annotation."
  index  : 8


-
  name: "movable_object.barrier"
  description: "Temporary road barrier placed in the scene in order to redirect traffic. Commonly used at construction sites. This includes concrete barrier, metal barrier and water barrier. No fences."
  index  : 9


-
  name: "movable_object.debris"
  description: "Movable object that is left on the driveable surface that is too large to be driven over safely, e.g tree branch, full trash bag etc."
  index  : 10


-
  name: "movable_object.pushable_pullable"
  description: "Objects that a pedestrian may push or pull. For example dolleys, wheel barrows, garbage-bins, or shopping carts."
  index  : 11


-
  name: "movable_object.trafficcone"
  description: "All types of traffic cone."
  index  : 12


-
  name: "static_object.bicycle_rack"
  description: "Area or device intended to park or secure the bicycles in a row. It includes all the bikes parked in it and any empty slots that are intended for parking bikes."
  index  : 13


-
  name: "vehicle.bicycle"
  description: "Human or electric powered 2-wheeled vehicle designed to travel at lower speeds either on road surface, sidewalks or bike paths."
  index  : 14


-
  name: "vehicle.bus.bendy"
  description: "Bendy bus subcategory. Annotate each section of the bendy bus individually."
  index  : 15


-
  name: "vehicle.bus.rigid"
  description: "Rigid bus subcategory."
  index  : 16


-
  name: "vehicle.car"
  description: "Vehicle designed primarily for personal use, e.g. sedans, hatch-backs, wagons, vans, mini-vans, SUVs and jeeps. If the vehicle is designed to carry more than 10 people use vehicle.bus. If it is primarily designed to haul cargo use vehicle.truck. "
  index  : 17


-
  name: "vehicle.construction"
  description: "Vehicles primarily designed for construction. Typically very slow moving or stationary. Cranes and extremities of construction vehicles are only included in annotations if they interfere with traffic. Trucks used to haul rocks or building materials are considered vehicle.truck rather than construction vehicles."
  index  : 18


-
  name: "vehicle.emergency.ambulance"
  description: "All types of ambulances."
  index  : 19


-
  name: "vehicle.emergency.police"
  description: "All types of police vehicles including police bicycles and motorcycles."
  index  : 20


-
  name: "vehicle.motorcycle"
  description: "Gasoline or electric powered 2-wheeled vehicle designed to move rapidly (at the speed of standard cars) on the road surface. This category includes all motorcycles, vespas and scooters."
  index  : 21


-
  name: "vehicle.trailer"
  description: "Any vehicle trailer, both for trucks, cars and bikes."
  index  : 22


-
  name: "vehicle.truck"
  description: "Vehicles primarily designed to haul cargo including pick-ups, lorrys, trucks and semi-tractors. Trailers hauled after a semi-tractor should be labeled as vehicle.trailer"
  index  : 23


-
  name: "flat.driveable_surface"
  description: "All paved or unpaved surfaces that a car can drive on with no concern of traffic rules."
  index  : 24


-
  name: "flat.other"
  description: "All other forms of horizontal ground-level structures that do not belong to any of driveable_surface, curb, sidewalk and terrain. Includes elevated parts of traffic islands, delimiters, rail tracks, stairs with at most 3 steps and larger bodies of water (lakes, rivers)."
  index  : 25


-
  name: "flat.sidewalk"
  description: "Sidewalk, pedestrian walkways, bike paths, etc. Part of the ground designated for pedestrians or cyclists. Sidewalks do **not** have to be next to a road."
  index  : 26


-
  name: "flat.terrain"
  description: "Natural horizontal surfaces such as ground level horizontal vegetation (< 20 cm tall), grass, rolling hills, soil, sand and gravel."
  index  : 27


-
  name: "static.manmade"
  description: "Includes man-made structures but not limited to: buildings, walls, guard rails, fences, poles, drainages, hydrants, flags, banners, street signs, electric circuit boxes, traffic lights, parking meters and stairs with more than 3 steps."
  index  : 28


-
  name: "static.other"
  description: "Points in the background that are not distinguishable, or objects that do not match any of the above labels."
  index  : 29


-
  name: "static.vegetation"
  description: "Any vegetation in the frame that is higher than the ground, including bushes, plants, potted plants, trees, etc. Only tall grass (> 20cm) is part of this, ground level grass is part of `terrain`."
  index  : 30


-
  name: "vehicle.ego"
  description: "The vehicle on which the cameras, radar and lidar are mounted, that is sometimes visible at the bottom of the image."
  index  : 31